---
title: "A Study Comparing Vaccination Population by Votes"
date: '2021-09-30'
description: Risk-Return of DJIA stocks
draft: no
keywords: ''
slug: US
categories:
- ''
- ''
---
  
  
  
```{r load-libraries, warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)  # Load ggplot2, dplyr, and all the other tidyverse packages
library(mosaic)
library(ggthemes)
library(lubridate)
library(fivethirtyeight)
library(here)
library(skimr)
library(janitor)
library(vroom)
library(tidyquant)
library(rvest) # to scrape wikipedia page
```

  
```{r,out.width="100%"}

url <- "https://en.wikipedia.org/wiki/Opinion_polling_for_the_2021_German_federal_election"

# similar graphs and analyses can be found at 
# https://www.theguardian.com/world/2021/jun/21/german-election-poll-tracker-who-will-be-the-next-chancellor
# https://www.economist.com/graphic-detail/who-will-succeed-angela-merkel


# get tables that exist on wikipedia page 
tables <- url %>% 
  read_html() %>% 
  html_nodes(css="table")


# parse HTML tables into a dataframe called polls 
# Use purr::map() to create a list of all tables in URL
polls <- map(tables, . %>% 
             html_table(fill=TRUE)%>% 
             janitor::clean_names())


# list of opinion polls
german_election_polls <- polls[[1]] %>% # the first table on the page contains the list of all opinions polls
  slice(2:(n()-1)) %>%  # drop the first row, as it contains again the variable names and last row that contains 2017 results
  mutate(
         # polls are shown to run from-to, e.g. 9-13 Aug 2021. We keep the last date, 13 Aug here, as the poll date
         # and we extract it by picking the last 11 characters from that field
         end_date = str_sub(fieldwork_date, -11),
         
         # end_date is still a string, so we convert it into a date object using lubridate::dmy()
         end_date = dmy(end_date),
         
         # we also get the month and week number from the date, if we want to do analysis by month- week, etc.
         month = month(end_date),
         week = isoweek(end_date)
         )


  ggplot(data = german_election_polls) + 
  
    geom_point(aes(x=end_date, y=union, col="Union"), alpha=2/10) + 
    geom_point(aes(x=end_date, y=spd, col='SPD'), alpha=2/10) +
    geom_point(aes(x=end_date, y=af_d, col='AfD'), alpha=2/10) +
    geom_point(aes(x=end_date, y=fdp,col='FDP'), alpha=2/10) +
    geom_point(aes(x=end_date, y=linke,col='Linke'), alpha=2/10) +
    geom_point(aes(x=end_date, y=grune,col='Grüne'), alpha=2/10) +
    
    geom_smooth(aes(x=end_date, y=union, col="Union"), size=0.5,se=FALSE) + 
    geom_smooth(aes(x=end_date, y=spd, col='SPD'), size=0.5, se=FALSE) +
    geom_smooth(aes(x=end_date, y=af_d, col='AfD'), size=0.5,  se=FALSE) +
    geom_smooth(aes(x=end_date, y=fdp, col='FDP'),  size=0.5, se=FALSE) +
    geom_smooth(aes(x=end_date, y=linke, col='Linke'),  size=0.5,se=FALSE) +
    geom_smooth(aes(x=end_date, y=grune, col='Grüne'),  size=0.5,se=FALSE) +
    
  scale_y_continuous(labels = function(x) paste0(x, "%")) + #y axes in percentages
  scale_x_date(breaks = "2 months",date_labels="%b %Y") + #format the dates on x axes+
  scale_color_discrete(breaks= c("Union", "SPD", "AfD","FDP","Linke","Grüne"))+ #Reorder items in legend 
  labs(title=NULL,x=NULL, y= NULL, colour="" ) #deleting axes and legend labels


```

